const express = require('express');
const router = express.Router();
const User = require('../models/user.js');
const logger = require('../utils/logger');

// Utility function to validate username
const isValidUsername = (username) => {
  const maxLength = 15;
  const usernameRegex = /^(?=.{1,15}$)[a-zA-Z][a-zA-Z0-9]*(?:[._]?[a-zA-Z0-9]+)*$/;

  // Disallow double dots or double underscores, and trailing/leading dot or underscore
  const hasInvalidPattern = /[._]{2,}|^[._]|[._]$/.test(username);

  return username.length <= maxLength &&
         usernameRegex.test(username) &&
         !hasInvalidPattern;
};

router.post('/update-username', async (req, res) => {
  const userId = req.user?.id; // Extracted from JWT middleware
  const { username } = req.body;

  if (!userId || !username) {
    logger.warn('Input validation failed', { errors: 'Missing userId (JWT) or username' });
    return res.status(400).json({ message: "Username is required." });
  }

  if (!isValidUsername(username)) {
    logger.warn('Invalid username format', { username });
    return res.status(400).json({
      message: "Invalid username. Only letters, numbers, underscores, and periods allowed. Max 15 characters. No emojis or special characters.",
    });
  }

  try {
    // Check if user already has a custom username (unchangeable rule)
    const currentUser = await User.findById(userId);
    if (!currentUser) {
      logger.warn('User not found', { userId });
      return res.status(404).json({ message: "User not found." });
    }

    // UPDATED LOGIC: Check if username is already customized instead of just existing
    if (currentUser.isUsernameCustom) {
      logger.warn('Username already customized - cannot change', { 
        userId, 
        existingUsername: currentUser.username 
      });
      return res.status(400).json({ 
        message: "Username has already been customized and cannot be changed again.",
        currentUsername: currentUser.username
      });
    }

    // Check if username is taken by another user
    const usernameExists = await User.findOne({ username });
    if (usernameExists && usernameExists._id.toString() !== userId) {
      logger.info('Username already taken', { username });
      return res.status(409).json({ message: "Username already taken." });
    }

    // Update username and mark as customized (one-time only)
    const updatedUser = await User.findByIdAndUpdate(
      userId,
      { 
        username,
        isUsernameCustom: true // Mark as customized to prevent future changes
      },
      { new: true }
    );

    logger.info('Username updated successfully', { 
      userId, 
      oldUsername: currentUser.username,
      newUsername: username,
      wasAutoGenerated: !currentUser.isUsernameCustom
    });

    res.status(200).json({ 
      message: "Username updated successfully. This was your one-time username change.", 
      user: {
        id: updatedUser._id,
        username: updatedUser.username,
        email: updatedUser.email
      }
    });

  } catch (error) {
    logger.error('Error updating username', { error: error.message, userId });
    res.status(500).json({ message: "Server error while updating username." });
  }
});

module.exports = router;